# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      # Instead install flyctl directly
      # - name: Setup Flyctl
      #   run: |
      #     curl -L https://fly.io/install.sh | sh
      #     export FLYCTL_INSTALL="/home/runner/.fly"
      #     export PATH="$FLYCTL_INSTALL/bin:$PATH"

      - name: Set Fly.io Secrets
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
            flyctl secrets set GOOGLE_OAUTH_CLIENT_ID=${{ secrets.GOOGLE_OAUTH_CLIENT_ID }} --app dwi
            flyctl secrets set GOOGLE_OAUTH_CLIENT_SECRET=${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }} --app dwi
            flyctl secrets set GHUB_OAUTH_CLIENT_ID=${{ secrets.GHUB_OAUTH_CLIENT_ID }} --app dwi
            flyctl secrets set GHUB_OAUTH_CLIENT_SECRET=${{ secrets.GHUB_OAUTH_CLIENT_SECRET }} --app dwi
      
      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}